### ISSUE TITLE
Make shooter angle code actually use a controller

### ISSUE THREAD

**Issue by Bobobalink** [Chantilly612Code/612-2016#152]
Ben's jank-as-hell discreet proportional controller is dumb and wrong, we're going use a real PID controller.

**Comment by WardBenjamin** [comment]
...eventually.

**Comment by ZachPerkins1** [comment]
..yes

**Comment by Ahmad-Bamba** [comment]
I'm reopening this because it's a good idea, but this isn't something that we should worry about until **after** competition. Don't make any super substantial code changes before Friday. It'll just create more unaccountable variables.

And as a side note, why is it that when we use Ben's stuff it's always really jank :P

**Comment by ZachPerkins1** [comment]
I'm re-closing this because the shooter angle code already uses a PID controller.

**Comment by ZachPerkins1** [comment]
Looking back, I suppose I should have specified that instead of just writing yes with two dots before it...

**Comment by WardBenjamin** [comment]
> And as a side note, why is it that when we use Ben's stuff it's always really jank :p

Not always, just when I'm in a hurry and we need an implementation. Honestly, my stuff would require like zero tuning compared to this, so it would have been better to wait for this until after the first compo and focus on shooter testing. But whatever, it's done.
