### ISSUE TITLE
QUESTION: Subsystem list

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2016#21]
So far, I think the list of subsystems is: drivetrain, defense mechanisms, defense locations, boulder mechanism.

Can anyone think of anything else based on the current design?

We should start wiki pages for these subsystems

**Comment by WardBenjamin** [comment]
At this point, I think we should have separate subsystems for the actual shooter (whatever it ends up being, mechanical is working on a few design prototypes) and for the actual intake for the shooter. Those will be on distinctly separate parts of the robot and could both be being used at once, which the subsystem..... system is not designed for. :stuck_out_tongue: 

Other than that, the list looks good and I can't think of anything else off the top of my head.

**Comment by ChampD** [comment]
Now that I know the actual design of the robot, I think the best way of doing subsystems is Drivetrain, Arm (for defenses), Intake, Shooter (I would hold back on coding this until we know what shooter type we have). We will also have a class for what different defenses are on the field at each game, so that the robot can navigate them "automatically".
